# Generated by Django 3.0.4 on 2022-02-06 23:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arhivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo')),
                ('documento', models.FileField(blank=True, null=True, upload_to='archivos', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'tb_archivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.CharField(blank=True, max_length=100, null=True, verbose_name='personal')),
                ('paciente', models.CharField(blank=True, max_length=100, null=True, verbose_name='paciente')),
                ('fecha', models.CharField(blank=True, max_length=10, null=True, verbose_name='fecha')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='motivo')),
                ('diagnostico', models.CharField(blank=True, max_length=200, null=True, verbose_name='diagnostico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'tb_consultas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Tratamiento')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'db_table': 'tb_foto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupaciòn')),
                ('sexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sexo')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('fechaNacimiento', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'tb_paciente',
                'ordering': ['cedula'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=2000, null=True, verbose_name='cedula')),
                ('fechaPagos', models.CharField(blank=True, max_length=10, null=True, verbose_name='fecha Pagos')),
                ('tipo', models.CharField(blank=True, max_length=2, null=True, verbose_name='tipo')),
                ('concepto', models.CharField(blank=True, max_length=200, null=True, verbose_name='concepto')),
                ('monto', models.CharField(blank=True, max_length=10, null=True, verbose_name='monto')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'tb_pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True, verbose_name='tipo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'tb_permisos',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='cedula')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='apellido')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='direccion')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo')),
                ('fechaIngreso', models.DateField(blank=True, max_length=20, null=True, verbose_name='fecha Ingreso')),
                ('sexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='sexo')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='telefono')),
                ('fechaNacimiento', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personales',
                'db_table': 'tb_personal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.CharField(blank=True, max_length=100, null=True, verbose_name='personal')),
                ('paciente', models.CharField(blank=True, max_length=100, null=True, verbose_name='paciente')),
                ('fechaInicio', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de inicio')),
                ('odontograma', models.CharField(blank=True, max_length=5000, null=True, verbose_name='odontograma')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='estado')),
                ('costo', models.CharField(blank=True, max_length=50, null=True, verbose_name='costo')),
                ('saldo', models.CharField(blank=True, max_length=50, null=True, verbose_name='saldo')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tb_tratamiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(blank=True, max_length=15, null=True, verbose_name='paciente')),
                ('fechaT', models.CharField(blank=True, max_length=10, null=True, verbose_name='fecha')),
                ('horaT', models.CharField(blank=True, max_length=20, null=True, verbose_name='hora')),
                ('estadoT', models.CharField(blank=True, max_length=10, null=True, verbose_name='estado')),
                ('enunciado', models.CharField(blank=True, max_length=20, null=True, verbose_name='enunciado')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'tb_turnos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AntecedentesPatologicos',
            fields=[
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_paciente.Paciente')),
                ('enfermedadesCardiacas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enfermedades Cardiacas')),
                ('presionArterial', models.CharField(blank=True, max_length=1, null=True, verbose_name='Presion Arterial')),
                ('transtornosSanguineos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Transtornos Sanguineos')),
                ('alergias', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alergias')),
                ('medicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Medicacion')),
                ('otrasEnfermedades', models.CharField(blank=True, max_length=200, null=True, verbose_name='Otras Enfermedades')),
            ],
            options={
                'verbose_name': 'Antecedente Patologico',
                'verbose_name_plural': 'Antecedentes Patologicos',
                'db_table': 'tb_antecedentesPatologicos',
                'ordering': ['cedula'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTratamiento',
            fields=[
                ('tratamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_paciente.Tratamiento')),
                ('personal', models.CharField(blank=True, max_length=200, null=True, verbose_name='personal')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha')),
                ('pieza', models.CharField(blank=True, max_length=200, null=True, verbose_name='pieza')),
                ('diagnosticoTratamiento', models.CharField(blank=True, max_length=200, null=True, verbose_name='diagnostico Tratamiento')),
                ('tratamientoRealizado', models.CharField(blank=True, max_length=200, null=True, verbose_name='tratamiento Realizado')),
            ],
            options={
                'verbose_name': 'Detalle Tratamiento',
                'verbose_name_plural': 'Detalles Tratamientos',
                'db_table': 'tb_detalleTratamiento',
                'ordering': ['tratamiento'],
            },
        ),
        migrations.CreateModel(
            name='SintomatologiaOral',
            fields=[
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_paciente.Paciente')),
                ('halitosis', models.CharField(blank=True, max_length=1, null=True, verbose_name='halitosis')),
                ('hipersensibilidad', models.CharField(blank=True, max_length=5, null=True, verbose_name='hipersensibilidad')),
                ('sangradoEncias', models.CharField(blank=True, max_length=1, null=True, verbose_name='sangrado Encias')),
                ('xerostomia', models.CharField(blank=True, max_length=1, null=True, verbose_name='xerostomia')),
                ('bruxismo', models.CharField(blank=True, max_length=1, null=True, verbose_name='bruxismo')),
            ],
            options={
                'verbose_name': 'Sintomatologia Oral',
                'verbose_name_plural': 'Sintomatologias Orales',
                'db_table': 'tb_sintomatologiaOral',
                'ordering': ['cedula'],
            },
        ),
    ]
